FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache openssl

COPY package.json package-lock.json ./
COPY tsconfig.base.json ./
COPY packages ./packages
COPY services ./services
COPY gateway ./gateway

RUN npm install

CMD ["echo", "override me"]